version: "3.7"

services:
  database_postgres:
    container_name: database_postgres
    image: postgres:14.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=artisan_ultimate
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/artisan_ultimate:/var/lib/postgresql/data
