/**
 * Artisan API
 * 4 U From Gerste
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AliveDto { 
    message: string;
    status: AliveDto.StatusEnum;
}
export namespace AliveDto {
    export type StatusEnum = 'DEVELOPMENT' | 'PRODUCTION';
    export const StatusEnum = {
        Development: 'DEVELOPMENT' as StatusEnum,
        Production: 'PRODUCTION' as StatusEnum
    };
}


