/**
 * Artisan API
 * 4 U From Gerste
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    firstname: string;
    familyname: string;
    email: string;
    birthday: string | null;
    datevMaNumber: number | null;
    sollArbeitszeit: number | null;
    wochenarbeitstage: number | null;
    urlaubstage: number | null;
    eintrittsdatum: string | null;
    austrittsdatum: string | null;
    state: CreateUserDto.StateEnum;
}
export namespace CreateUserDto {
    export type StateEnum = 'active' | 'inactive';
    export const StateEnum = {
        Active: 'active' as StateEnum,
        Inactive: 'inactive' as StateEnum
    };
}


