/**
 * Artisan API
 * 4 U From Gerste
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HelloDto { 
    message: string;
    status: HelloDto.StatusEnum;
}
export namespace HelloDto {
    export type StatusEnum = 'SUCCESS' | 'ERROR' | 'WARNING';
    export const StatusEnum = {
        Success: 'SUCCESS' as StatusEnum,
        Error: 'ERROR' as StatusEnum,
        Warning: 'WARNING' as StatusEnum
    };
}


