/**
 * Artisan API
 * 4 U From Gerste
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserDto { 
    firstname: string;
    familyname: string;
    email: string;
    birthday?: string | null;
    datevMaNumber?: number;
    sollArbeitszeit?: number;
    wochenarbeitstage?: number;
    urlaubstage?: number;
    eintrittsdatum?: string;
    austrittsdatum?: string;
    state?: UpdateUserDto.StateEnum;
}
export namespace UpdateUserDto {
    export type StateEnum = 'active' | 'inactive';
    export const StateEnum = {
        Active: 'active' as StateEnum,
        Inactive: 'inactive' as StateEnum
    };
}


